name: test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1.1.1

      - name: Installing and Running Tests
      - run: |
          cd server
          bun install
          bun test
